// Auto-generated. Do not edit!

// (in-package second_coursework.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class PatrolResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.person_poses = null;
      this.cat_poses = null;
      this.dog_poses = null;
    }
    else {
      if (initObj.hasOwnProperty('person_poses')) {
        this.person_poses = initObj.person_poses
      }
      else {
        this.person_poses = [];
      }
      if (initObj.hasOwnProperty('cat_poses')) {
        this.cat_poses = initObj.cat_poses
      }
      else {
        this.cat_poses = [];
      }
      if (initObj.hasOwnProperty('dog_poses')) {
        this.dog_poses = initObj.dog_poses
      }
      else {
        this.dog_poses = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PatrolResult
    // Serialize message field [person_poses]
    // Serialize the length for message field [person_poses]
    bufferOffset = _serializer.uint32(obj.person_poses.length, buffer, bufferOffset);
    obj.person_poses.forEach((val) => {
      bufferOffset = geometry_msgs.msg.Pose.serialize(val, buffer, bufferOffset);
    });
    // Serialize message field [cat_poses]
    // Serialize the length for message field [cat_poses]
    bufferOffset = _serializer.uint32(obj.cat_poses.length, buffer, bufferOffset);
    obj.cat_poses.forEach((val) => {
      bufferOffset = geometry_msgs.msg.Pose.serialize(val, buffer, bufferOffset);
    });
    // Serialize message field [dog_poses]
    // Serialize the length for message field [dog_poses]
    bufferOffset = _serializer.uint32(obj.dog_poses.length, buffer, bufferOffset);
    obj.dog_poses.forEach((val) => {
      bufferOffset = geometry_msgs.msg.Pose.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PatrolResult
    let len;
    let data = new PatrolResult(null);
    // Deserialize message field [person_poses]
    // Deserialize array length for message field [person_poses]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.person_poses = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.person_poses[i] = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset)
    }
    // Deserialize message field [cat_poses]
    // Deserialize array length for message field [cat_poses]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.cat_poses = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.cat_poses[i] = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset)
    }
    // Deserialize message field [dog_poses]
    // Deserialize array length for message field [dog_poses]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.dog_poses = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.dog_poses[i] = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 56 * object.person_poses.length;
    length += 56 * object.cat_poses.length;
    length += 56 * object.dog_poses.length;
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'second_coursework/PatrolResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '36b4977d3d4e148dd8c6328523d75894';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    geometry_msgs/Pose[] person_poses
    geometry_msgs/Pose[] cat_poses
    geometry_msgs/Pose[] dog_poses
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PatrolResult(null);
    if (msg.person_poses !== undefined) {
      resolved.person_poses = new Array(msg.person_poses.length);
      for (let i = 0; i < resolved.person_poses.length; ++i) {
        resolved.person_poses[i] = geometry_msgs.msg.Pose.Resolve(msg.person_poses[i]);
      }
    }
    else {
      resolved.person_poses = []
    }

    if (msg.cat_poses !== undefined) {
      resolved.cat_poses = new Array(msg.cat_poses.length);
      for (let i = 0; i < resolved.cat_poses.length; ++i) {
        resolved.cat_poses[i] = geometry_msgs.msg.Pose.Resolve(msg.cat_poses[i]);
      }
    }
    else {
      resolved.cat_poses = []
    }

    if (msg.dog_poses !== undefined) {
      resolved.dog_poses = new Array(msg.dog_poses.length);
      for (let i = 0; i < resolved.dog_poses.length; ++i) {
        resolved.dog_poses[i] = geometry_msgs.msg.Pose.Resolve(msg.dog_poses[i]);
      }
    }
    else {
      resolved.dog_poses = []
    }

    return resolved;
    }
};

module.exports = PatrolResult;
