// Auto-generated. Do not edit!

// (in-package second_coursework.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PatrolGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.patrol_duration = null;
    }
    else {
      if (initObj.hasOwnProperty('patrol_duration')) {
        this.patrol_duration = initObj.patrol_duration
      }
      else {
        this.patrol_duration = {secs: 0, nsecs: 0};
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PatrolGoal
    // Serialize message field [patrol_duration]
    bufferOffset = _serializer.duration(obj.patrol_duration, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PatrolGoal
    let len;
    let data = new PatrolGoal(null);
    // Deserialize message field [patrol_duration]
    data.patrol_duration = _deserializer.duration(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'second_coursework/PatrolGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '41044496e55fc1dcdb646ab97e22a074';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # action/PatrolAction.action
    # Goal
    duration patrol_duration
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PatrolGoal(null);
    if (msg.patrol_duration !== undefined) {
      resolved.patrol_duration = msg.patrol_duration;
    }
    else {
      resolved.patrol_duration = {secs: 0, nsecs: 0}
    }

    return resolved;
    }
};

module.exports = PatrolGoal;
