// Generated by gencpp from file second_coursework/PatrolResult.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_PATROLRESULT_H
#define SECOND_COURSEWORK_MESSAGE_PATROLRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace second_coursework
{
template <class ContainerAllocator>
struct PatrolResult_
{
  typedef PatrolResult_<ContainerAllocator> Type;

  PatrolResult_()
    : person_poses()
    , cat_poses()
    , dog_poses()  {
    }
  PatrolResult_(const ContainerAllocator& _alloc)
    : person_poses(_alloc)
    , cat_poses(_alloc)
    , dog_poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _person_poses_type;
  _person_poses_type person_poses;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _cat_poses_type;
  _cat_poses_type cat_poses;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _dog_poses_type;
  _dog_poses_type dog_poses;





  typedef boost::shared_ptr< ::second_coursework::PatrolResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::PatrolResult_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolResult_

typedef ::second_coursework::PatrolResult_<std::allocator<void> > PatrolResult;

typedef boost::shared_ptr< ::second_coursework::PatrolResult > PatrolResultPtr;
typedef boost::shared_ptr< ::second_coursework::PatrolResult const> PatrolResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::PatrolResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::PatrolResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_coursework::PatrolResult_<ContainerAllocator1> & lhs, const ::second_coursework::PatrolResult_<ContainerAllocator2> & rhs)
{
  return lhs.person_poses == rhs.person_poses &&
    lhs.cat_poses == rhs.cat_poses &&
    lhs.dog_poses == rhs.dog_poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_coursework::PatrolResult_<ContainerAllocator1> & lhs, const ::second_coursework::PatrolResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::PatrolResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::PatrolResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::PatrolResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::PatrolResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::PatrolResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::PatrolResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::PatrolResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36b4977d3d4e148dd8c6328523d75894";
  }

  static const char* value(const ::second_coursework::PatrolResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36b4977d3d4e148dULL;
  static const uint64_t static_value2 = 0xd8c6328523d75894ULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::PatrolResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/PatrolResult";
  }

  static const char* value(const ::second_coursework::PatrolResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::PatrolResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"geometry_msgs/Pose[] person_poses\n"
"geometry_msgs/Pose[] cat_poses\n"
"geometry_msgs/Pose[] dog_poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::second_coursework::PatrolResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::PatrolResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.person_poses);
      stream.next(m.cat_poses);
      stream.next(m.dog_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::PatrolResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_coursework::PatrolResult_<ContainerAllocator>& v)
  {
    s << indent << "person_poses[]" << std::endl;
    for (size_t i = 0; i < v.person_poses.size(); ++i)
    {
      s << indent << "  person_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.person_poses[i]);
    }
    s << indent << "cat_poses[]" << std::endl;
    for (size_t i = 0; i < v.cat_poses.size(); ++i)
    {
      s << indent << "  cat_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.cat_poses[i]);
    }
    s << indent << "dog_poses[]" << std::endl;
    for (size_t i = 0; i < v.dog_poses.size(); ++i)
    {
      s << indent << "  dog_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.dog_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_PATROLRESULT_H
