// Generated by gencpp from file second_coursework/PatrolGoal.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_PATROLGOAL_H
#define SECOND_COURSEWORK_MESSAGE_PATROLGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_coursework
{
template <class ContainerAllocator>
struct PatrolGoal_
{
  typedef PatrolGoal_<ContainerAllocator> Type;

  PatrolGoal_()
    : patrol_duration()  {
    }
  PatrolGoal_(const ContainerAllocator& _alloc)
    : patrol_duration()  {
  (void)_alloc;
    }



   typedef ros::Duration _patrol_duration_type;
  _patrol_duration_type patrol_duration;





  typedef boost::shared_ptr< ::second_coursework::PatrolGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::PatrolGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolGoal_

typedef ::second_coursework::PatrolGoal_<std::allocator<void> > PatrolGoal;

typedef boost::shared_ptr< ::second_coursework::PatrolGoal > PatrolGoalPtr;
typedef boost::shared_ptr< ::second_coursework::PatrolGoal const> PatrolGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::PatrolGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::PatrolGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_coursework::PatrolGoal_<ContainerAllocator1> & lhs, const ::second_coursework::PatrolGoal_<ContainerAllocator2> & rhs)
{
  return lhs.patrol_duration == rhs.patrol_duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_coursework::PatrolGoal_<ContainerAllocator1> & lhs, const ::second_coursework::PatrolGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::PatrolGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::PatrolGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::PatrolGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::PatrolGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::PatrolGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::PatrolGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::PatrolGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41044496e55fc1dcdb646ab97e22a074";
  }

  static const char* value(const ::second_coursework::PatrolGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41044496e55fc1dcULL;
  static const uint64_t static_value2 = 0xdb646ab97e22a074ULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::PatrolGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/PatrolGoal";
  }

  static const char* value(const ::second_coursework::PatrolGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::PatrolGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# action/PatrolAction.action\n"
"# Goal\n"
"duration patrol_duration\n"
;
  }

  static const char* value(const ::second_coursework::PatrolGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::PatrolGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.patrol_duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::PatrolGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_coursework::PatrolGoal_<ContainerAllocator>& v)
  {
    s << indent << "patrol_duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.patrol_duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_PATROLGOAL_H
