// Generated by gencpp from file second_coursework/YOLOLastFrameRequest.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAMEREQUEST_H
#define SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_coursework
{
template <class ContainerAllocator>
struct YOLOLastFrameRequest_
{
  typedef YOLOLastFrameRequest_<ContainerAllocator> Type;

  YOLOLastFrameRequest_()
    {
    }
  YOLOLastFrameRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct YOLOLastFrameRequest_

typedef ::second_coursework::YOLOLastFrameRequest_<std::allocator<void> > YOLOLastFrameRequest;

typedef boost::shared_ptr< ::second_coursework::YOLOLastFrameRequest > YOLOLastFrameRequestPtr;
typedef boost::shared_ptr< ::second_coursework::YOLOLastFrameRequest const> YOLOLastFrameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/YOLOLastFrameRequest";
  }

  static const char* value(const ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YOLOLastFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::second_coursework::YOLOLastFrameRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAMEREQUEST_H
