// Generated by gencpp from file second_coursework/YOLOLastFrameResponse.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAMERESPONSE_H
#define SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAMERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <second_coursework/YOLODetection.h>

namespace second_coursework
{
template <class ContainerAllocator>
struct YOLOLastFrameResponse_
{
  typedef YOLOLastFrameResponse_<ContainerAllocator> Type;

  YOLOLastFrameResponse_()
    : detections()  {
    }
  YOLOLastFrameResponse_(const ContainerAllocator& _alloc)
    : detections(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::second_coursework::YOLODetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::second_coursework::YOLODetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct YOLOLastFrameResponse_

typedef ::second_coursework::YOLOLastFrameResponse_<std::allocator<void> > YOLOLastFrameResponse;

typedef boost::shared_ptr< ::second_coursework::YOLOLastFrameResponse > YOLOLastFrameResponsePtr;
typedef boost::shared_ptr< ::second_coursework::YOLOLastFrameResponse const> YOLOLastFrameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator1> & lhs, const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator1> & lhs, const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3df913089db15baa8d0e578ec1d4f61";
  }

  static const char* value(const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3df913089db15baULL;
  static const uint64_t static_value2 = 0xa8d0e578ec1d4f61ULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/YOLOLastFrameResponse";
  }

  static const char* value(const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/YOLODetection[] detections\n"
"\n"
"================================================================================\n"
"MSG: second_coursework/YOLODetection\n"
"string name\n"
"float32 confidence\n"
"uint32 bbox_x\n"
"uint32 bbox_y\n"
"uint32 width\n"
"uint32 height\n"
;
  }

  static const char* value(const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YOLOLastFrameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_coursework::YOLOLastFrameResponse_<ContainerAllocator>& v)
  {
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::second_coursework::YOLODetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAMERESPONSE_H
