// Generated by gencpp from file second_coursework/YOLOLastFrame.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAME_H
#define SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAME_H

#include <ros/service_traits.h>


#include <second_coursework/YOLOLastFrameRequest.h>
#include <second_coursework/YOLOLastFrameResponse.h>


namespace second_coursework
{

struct YOLOLastFrame
{

typedef YOLOLastFrameRequest Request;
typedef YOLOLastFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct YOLOLastFrame
} // namespace second_coursework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::second_coursework::YOLOLastFrame > {
  static const char* value()
  {
    return "f3df913089db15baa8d0e578ec1d4f61";
  }

  static const char* value(const ::second_coursework::YOLOLastFrame&) { return value(); }
};

template<>
struct DataType< ::second_coursework::YOLOLastFrame > {
  static const char* value()
  {
    return "second_coursework/YOLOLastFrame";
  }

  static const char* value(const ::second_coursework::YOLOLastFrame&) { return value(); }
};


// service_traits::MD5Sum< ::second_coursework::YOLOLastFrameRequest> should match
// service_traits::MD5Sum< ::second_coursework::YOLOLastFrame >
template<>
struct MD5Sum< ::second_coursework::YOLOLastFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::second_coursework::YOLOLastFrame >::value();
  }
  static const char* value(const ::second_coursework::YOLOLastFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_coursework::YOLOLastFrameRequest> should match
// service_traits::DataType< ::second_coursework::YOLOLastFrame >
template<>
struct DataType< ::second_coursework::YOLOLastFrameRequest>
{
  static const char* value()
  {
    return DataType< ::second_coursework::YOLOLastFrame >::value();
  }
  static const char* value(const ::second_coursework::YOLOLastFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::second_coursework::YOLOLastFrameResponse> should match
// service_traits::MD5Sum< ::second_coursework::YOLOLastFrame >
template<>
struct MD5Sum< ::second_coursework::YOLOLastFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::second_coursework::YOLOLastFrame >::value();
  }
  static const char* value(const ::second_coursework::YOLOLastFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_coursework::YOLOLastFrameResponse> should match
// service_traits::DataType< ::second_coursework::YOLOLastFrame >
template<>
struct DataType< ::second_coursework::YOLOLastFrameResponse>
{
  static const char* value()
  {
    return DataType< ::second_coursework::YOLOLastFrame >::value();
  }
  static const char* value(const ::second_coursework::YOLOLastFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_YOLOLASTFRAME_H
