(cl:defpackage second_coursework-msg
  (:use )
  (:export
   "<EMERGENCY>"
   "EMERGENCY"
   "<PATROLACTION>"
   "PATROLACTION"
   "<PATROLACTIONFEEDBACK>"
   "PATROLACTIONFEEDBACK"
   "<PATROLACTIONGOAL>"
   "PATROLACTIONGOAL"
   "<PATROLACTIONRESULT>"
   "PATROLACTIONRESULT"
   "<PATROLFEEDBACK>"
   "PATROLFEEDBACK"
   "<PATROLGOAL>"
   "PATROLGOAL"
   "<PATROLRESULT>"
   "PATROLRESULT"
   "<YOLODETECTION>"
   "YOLODETECTION"
  ))

