# Goal
duration patrol_duration
---
# Result
geometry_msgs/Pose[] person_poses
geometry_msgs/Pose[] cat_poses
geometry_msgs/Pose[] dog_poses
---
# Feedback
int32 new_people
int32 new_cats
int32 new_dogs
geometry_msgs/Pose last_detection_pose